apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cs
  name: cs-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs-backend
  template:
    metadata:
      labels:
        app: cs-backend
    spec:
      imagePullSecrets:
      - name: evomg-cr
      containers:
        - name: cs-backend
          image: IMAGE 
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
               name: cs-backend-secrets
