apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs-backend
  template:
    metadata:
      labels:
        app: cs-backend
    spec:
      containers:
        - name: cs-backend
          image: IMAGE # Replace with your actual image
          ports:
            - containerPort: 8020
          volumeMounts:
            - name: cs-backend-volume
              mountPath: /app
          envFrom:
            - configMapRef:
                name: cs-backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: cs-backend-service
spec:
  selector:
    app: cs-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8020
