apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs-backend
  template:
    metadata:
      labels:
        app: cs-backend
    spec:
      imagePullSecrets:
      - name: evomg-cr
      containers:
      - name: cs-backend
        image: IMAGE
        ports:
        - containerPort: 8020
        readinessProbe:
          httpGet:
            path: /
            port: 8020
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 500Mi
