apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-pv
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/pvc/cs-api

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
