apiVersion: v1
data:
  BSC_NODE_URL: aHR0cHM6Ly9ic2MtZGF0YXNlZWQuYmluYW5jZS5vcmcv
  BSCSCAN_API_KEY: V0kzVE1ON0RERkUxM1FTVk42R1JHUkFGVzJIUk5XVEQ5Sw==
  BSCSCAN_BASE_URL: aHR0cHM6Ly9hcGkuYnNjc2Nhbi5jb20=
  CELERY_BACKEND_URL: cmVkaXM6Ly9kZWZhdWx0OkFWTlNfeEdaZGJ0eGwzYzhZbnVIVEpsZkBwcml2YXRlLXJlZGlzLWRldi1kby11c2VyLTExMTA1OTAzLTAuYy5kYi5vbmRpZ2l0YWxvY2Vhbi5jb206MjUwNjEvY3M=
  CELERY_BROKER_URL: cmVkaXM6Ly9kZWZhdWx0OkFWTlNfeEdaZGJ0eGwzYzhZbnVIVEpsZkBwcml2YXRlLXJlZGlzLWRldi1kby11c2VyLTExMTA1OTAzLTAuYy5kYi5vbmRpZ2l0YWxvY2Vhbi5jb206MjUwNjEvY3M=
  CELERY_RESULT_BACKEND: cmVkaXM6Ly9kZWZhdWx0OkFWTlNfeEdaZGJ0eGwzYzhZbnVIVEpsZkBwcml2YXRlLXJlZGlzLWRldi1kby11c2VyLTExMTA1OTAzLTAuYy5kYi5vbmRpZ2l0YWxvY2Vhbi5jb206MjUwNjEvY3M=
  COMPOSE_PROJECT_NAME: Y3NfYmFja2VuZA==
  CORPORATE_CONTRACT_ADMIN_ADDRESS: MHhlY2ZEZDU5NkUxNzMyMDQ2NzY0RWIyNUVFODk1RDkxREE0NDk4REM2
  CORPORATE_CONTRACT_ADMIN_PRIVATE_KEY: ZTQzNDU2YWQ3ODAwZTIzMWRhNDdmNDRlMzIyYTkzM2E3YjYzOWE3NzFiNzBjZTYwNWExNjZiNTNiY2Y0NGNiMA==
  CORPORATE_PAYOUTS_CONTRACT_ADDRESS: MHhFOTdENzg0NjE3QjE4Nzc3QjQ1NDMyODBDMDMyMTUzQzlkODQ4ODY0
  DB_HOST: cHJpdmF0ZS1ldm9tZy1wb3N0Z3Jlcy1kZXYtZG8tdXNlci0xMTEwNTkwMy0wLmMuZGIub25kaWdpdGFsb2NlYW4uY29t
  DB_NAME: Y3MtdGVzdA==
  DB_PASSWORD: QVZOU19DcmMzN1Q0S0dzNDRYV00xcmpW
  DB_PORT: MjUwNjA=
  DB_USERNAME: ZG9hZG1pbg==
  FACEIT_API_KEY: MmE0ZTM2NDAtNWIyZi00MWE4LTliZTQtNzU2NDc2Y2ZhMGQ2
  IS_PROD: ZmFsc2U=
  JWT_SECRET_KEY: OWY2M2QzMjE0ZGE5MmM0NWE0MGQzODY2YTVmYjkzZTk5OGFmY2E3NTNhNTU3ZmVlMGRlN2JhOGQ2NTUxNzY3Yw==
  LEADERBOARD_ID: NjUxZGEzMWFmM2U5NmQyMDQ0YTM1MzY2
  OAUTH_AUTHORIZE_REDIRECT_PATH: aHR0cHM6Ly9jczItYmFja2VuZC5ldm9tLmRldi9iYWNrZW5kL2FwaS92MS91c2Vycy9sb2dpbi9jYWxsYmFjaw==
  OAUTH_CLIENT_ID: MjZlM2UxY2UtMDUxYi00YWFkLWFjN2MtNzRiMmNlM2Y1ZmZh
  OAUTH_CLIENT_SECRET: TzA5Wnpxelgzcml4Q2c2RFg4Z1N6OGlGajhiWjdCdXVnR0hmdGx5UA==
kind: Secret
metadata:
  name: cs-backend-secrets
  namespace: cs
type: Opaque
