apiVersion: v1
kind: Service
metadata:
  namespace: cs
  name: cs-backend-celery-service
spec:
  selector:
    app: cs-backend-celery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8020
