"""empty message

Revision ID: 0048f137583b
Revises: 10b3b2c1320c
Create Date: 2023-12-09 22:33:27.140599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0048f137583b'
down_revision: Union[str, None] = '10b3b2c1320c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift_events', sa.Column('season_name', sa.String(), nullable=True))
    op.add_column('gift_events', sa.Column('is_approved', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gift_events', 'is_approved')
    op.drop_column('gift_events', 'season_name')
    # ### end Alembic commands ###
