"""Add gift

Revision ID: 4854cab34304
Revises: 5a94dc0d0c50
Create Date: 2023-12-01 11:05:24.424468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4854cab34304'
down_revision: Union[str, None] = '5a94dc0d0c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
gift_status = sa.Enum('IN_PROGRESS', 'DONE', name='gift_status')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', postgresql.ENUM('IN_PROGRESS', 'DONE', name='gift_status'), nullable=False),
    sa.Column('start_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('top_one_count', sa.Integer(), nullable=True),
    sa.Column('top_two_count', sa.Integer(), nullable=True),
    sa.Column('top_three_count', sa.Integer(), nullable=True),
    sa.Column('top_four_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_events_id'), 'gift_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gift_events_id'), table_name='gift_events')
    op.drop_table('gift_events')
    # ### end Alembic commands ###
