"""Init DB

Revision ID: 4f751b526eac
Revises: 
Create Date: 2023-11-03 18:35:56.989322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f751b526eac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('banned', sa.Boolean(), nullable=True),
    sa.Column('money_count', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_id'), 'billing', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('openid', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('ethereum_ID', sa.String(), nullable=True),
    sa.Column('billing_model', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['billing_model'], ['billing.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ethereum_ID'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('openid')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_billing_id'), table_name='billing')
    op.drop_table('billing')
    # ### end Alembic commands ###
