"""aaa

Revision ID: 5a94dc0d0c50
Revises: e4979acdf01b
Create Date: 2023-12-01 08:57:22.840503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a94dc0d0c50'
down_revision: Union[str, None] = 'e4979acdf01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

transaction_type = sa.Enum('EMPTY', 'FROZEN', 'UNFROZEN', 'WITHDRAW', 'GIFT', name='transaction_type')
withdraw_request_type = sa.Enum('EMPTY', 'IN_PROGRESS', 'DONE', 'FAILED', name='withdraw_request_type')


def upgrade() -> None:
    transaction_type.create(op.get_bind())
    withdraw_request_type.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('type', postgresql.ENUM('EMPTY', 'FROZEN', 'UNFROZEN', 'WITHDRAW', 'GIFT', name='transaction_type'), nullable=False))
    op.add_column('withdraw_request', sa.Column('status', postgresql.ENUM('EMPTY', 'IN_PROGRESS', 'DONE', 'FAILED', name='withdraw_request_type'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdraw_request', 'status')
    op.drop_column('transaction', 'type')
    # ### end Alembic commands ###
