"""asd

Revision ID: 5c10173c81c1
Revises: 4854cab34304
Create Date: 2023-12-01 11:28:25.981277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c10173c81c1'
down_revision: Union[str, None] = '4854cab34304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift_events', sa.Column('leaderboard_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gift_events', 'leaderboard_id')
    # ### end Alembic commands ###
