"""check

Revision ID: 8c79a7b819a2
Revises: 8c839f3a2cc1
Create Date: 2023-12-01 00:10:36.486499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c79a7b819a2'
down_revision: Union[str, None] = '8c839f3a2cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdraw_check',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tx_hash', sa.String(length=255), nullable=False),
    sa.Column('tx_blockNumber', sa.String(length=255), nullable=False),
    sa.Column('tx_from', sa.String(length=255), nullable=False),
    sa.Column('tx_to', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdraw_check_id'), 'withdraw_check', ['id'], unique=False)
    op.create_table('withdraw_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('tx_hash', sa.String(length=255), nullable=True),
    sa.Column('transaction_block_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['billing_account.id'], ),
    sa.ForeignKeyConstraint(['transaction_block_id'], ['transaction_block.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdraw_request_id'), 'withdraw_request', ['id'], unique=False)
    op.alter_column('transaction', 'type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_withdraw_request_id'), table_name='withdraw_request')
    op.drop_table('withdraw_request')
    op.drop_index(op.f('ix_withdraw_check_id'), table_name='withdraw_check')
    op.drop_table('withdraw_check')
    # ### end Alembic commands ###
