name: Deploy to Kubernetes

on:
  push:
    branches:
      - Main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
        
      - name: Build container image
        run: docker build -t registry.digitalocean.com/evomg-cr/cs-backend:$(echo $GITHUB_SHA | head -c7) .

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/evomg-cr/cs-backend:$(echo $GITHUB_SHA | head -c7)

      - name: Update deployment file
        run: TAG=$(echo $GITHUB_SHA | head -c7) && sed -i 's|IMAGE|registry.digitalocean.com/evomg-cr/cs-backend:'${TAG}'|' k8s/deployment.yaml

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 evomg-k8s

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f k8s/deployment.yaml

      - name: Verify deployment
        run: kubectl rollout status deployment/cs-backend-deployment

      - name: Apply service file if there is any updates
        run: | 
          kubectl apply -f k8s/service.yaml 
      - name: Apply service file if there is any updates
        run: | 
          kubectl apply -f k8s/pvc.yaml 
