name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy_api:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
          
      - name: Load ENV for the app
        run: |
          echo -E '${{ secrets.PROD_ENV_FILE }}' > docker/env_files/.env

      - name: Load ENV for the app
        run: |
          cat docker/env_files/.env | base64
          
        
      - name: Build container image
        run: docker build -t registry.digitalocean.com/evomg-cr/cs-backend:$(echo $GITHUB_SHA | head -c7) -f docker/api/Dockerfile .

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Update deployment file
        run: TAG=$(echo $GITHUB_SHA | head -c7) && sed -i 's|IMAGE|registry.digitalocean.com/evomg-cr/cs-backend:'${TAG}'|' k8s/deployment.yaml

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/evomg-cr/cs-backend:$(echo $GITHUB_SHA | head -c7)

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 evomg-k8s

      - name: Apply namespace
        run: kubectl apply -f k8s/namespace.yaml

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f k8s/deployment.yaml

      - name: Verify deployment
        run: kubectl rollout status deployment/cs-backend-deployment -n cs

      - name: Apply service file if there is any updates
        run: | 
          kubectl apply -f k8s/service.yaml 
          
      - name: Apply ingress file if there is any updates
        run: | 
          kubectl apply -f k8s/ingress-prod.yaml 

      - name: Remove old images from Container Registry
        uses: ripplr-io/docr-image-remove@v1
        with:
          image_repository: cs-backend
          buffer_size: 5          

  deploy_worker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
        
      - name: Load ENV for the app
        run: |
          echo -E '${{ secrets.PROD_ENV_FILE }}' > docker/env_files/.env
        
      - name: Build container image
        run: docker build -t registry.digitalocean.com/evomg-cr/cs-backend-celery:$(echo $GITHUB_SHA | head -c7) -f docker/api/DockerfileCelery .

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Update deployment file
        run: TAG=$(echo $GITHUB_SHA | head -c7) && sed -i 's|IMAGE|registry.digitalocean.com/evomg-cr/cs-backend-celery:'${TAG}'|' k8s/deployment-celery.yaml

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/evomg-cr/cs-backend-celery:$(echo $GITHUB_SHA | head -c7)

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 evomg-k8s

      - name: Apply namespace
        run: kubectl apply -f k8s/namespace.yaml

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f k8s/deployment-celery.yaml

      - name: Verify deployment
        run: kubectl rollout status deployment/cs-backend-celery-deployment -n cs

      - name: Apply service file if there is any updates
        run: | 
          kubectl apply -f k8s/service-celery.yaml 
          
      - name: Remove old images from Container Registry
        uses: ripplr-io/docr-image-remove@v1
        with:
          image_repository: cs-backend-celery
          buffer_size: 5          
