name: Deploy to Kubernetes

on:
  push:
    branches:
      - '*dev*'

jobs:
  deploy_api:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
                  
      - name: Build container image
        run: docker build -t registry.digitalocean.com/evomg-cr/cs-backend-dev:$(echo $GITHUB_SHA | head -c7) -f docker/api/Dockerfile .

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Update deployment file
        run: TAG=$(echo $GITHUB_SHA | head -c7) && sed -i 's|IMAGE|registry.digitalocean.com/evomg-cr/cs-backend-dev:'${TAG}'|' k8s/deployment.yaml

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/evomg-cr/cs-backend-dev:$(echo $GITHUB_SHA | head -c7)

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 evomg-dev

      - name: Apply namespace
        run: kubectl apply -f k8s/namespace.yaml

      - name: Apply secrets
        run: kubectl apply -f k8s/secrets-dev.yaml

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f k8s/deployment.yaml

      - name: Verify deployment
        run: kubectl rollout status deployment/cs-backend-deployment -n cs

      - name: Apply service file if there is any updates
        run: | 
          kubectl apply -f k8s/service.yaml 
          
      - name: Apply ingress file if there is any updates
        run: | 
          kubectl apply -f k8s/ingress-dev.yaml 

      - name: Remove old images from Container Registry
        uses: ripplr-io/docr-image-remove@v1
        with:
          image_repository: cs-backend-dev
          buffer_size: 5          

  deploy_worker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
                
      - name: Build container image
        run: docker build -t registry.digitalocean.com/evomg-cr/cs-backend-celery-dev:$(echo $GITHUB_SHA | head -c7) -f docker/api/DockerfileCelery .

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Update deployment file
        run: TAG=$(echo $GITHUB_SHA | head -c7) && sed -i 's|IMAGE|registry.digitalocean.com/evomg-cr/cs-backend-celery-dev:'${TAG}'|' k8s/deployment-celery.yaml

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/evomg-cr/cs-backend-celery-dev:$(echo $GITHUB_SHA | head -c7)

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 evomg-dev

      - name: Apply namespace
        run: kubectl apply -f k8s/namespace.yaml

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f k8s/deployment-celery.yaml

      - name: Verify deployment
        run: kubectl rollout status deployment/cs-backend-celery-deployment -n cs

      - name: Apply service file if there is any updates
        run: | 
          kubectl apply -f k8s/service-celery.yaml 
      
      - name: Remove old images from Container Registry
        uses: ripplr-io/docr-image-remove@v1
        with:
          image_repository: cs-backend-celery-dev
          buffer_size: 5          
          